### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by DrewCZ** [Frvetz/FS22_RealisticDamageSystem#2]
Hi Frvetz! Sounds excellent, thank you for pushing away from Arcade mode! We try to play realistic, so have 2 questions.
1. Is there any way how to suppress message when engine stall or doesn't start? For example switch the engine state to ENGINESTOP and only displays to ENGINESTARTING? It will lit the lamps but no engine start processing. I'm looking for suppress that ugly game messages over whole screen. 
2. Will be possible to make an emergency repair, i.e. on the field during harvest in the workshop closing time? It is normal that service is available 24/7 for extended price for workers. We are using mod with hand tool, which can open workshop menu anywhere. How it will work with your mod? 

Thank you.

**Comment by Frvetz** [comment]
Hi Drew!

1. I think I have to admit that I don't quite understand what you mean... But if you are asking if there is a way to permanently disable the "Please start the engine first" text, then yes. But only via script... For example, I deactivate this text to be able to display my "EngineStalled" warning
2. That is an excellent idea! Currently there is no such function implemented and the workshop mod doesn't replace my maintenance pallet but I think the emergency repair is an awesome feature! I'm not sure if you mean the "FS22_MobileWorkshop" mod but maybe I can implement a similar function where you can access the maintenance menu from outside the vehicle to call a worker and start an emergency repair with higher costs?

Kindest Regards
Gerrit

**Comment by DrewCZ** [comment]
Hi, 
@ 1. - sorry for my confusing description. Simply, I'm looking to suppress those ugly game messages over the whole screen. It's not related (or against) to you or your mod exactly. But because you are a magician I'm asking you for help. 
If you really can hide the messages over the screen, it will be pretty good to have an option, mean the setting of your mod, where these messages can be permanently hidden/suppressed. And as a x-mass gift, you can also hide that "start engine first" message. It is because as very skilled players, we know that the engine is not running or not started, but the game doesn't know that we are such good drivers :-D 

@ 2. - I'm so glad that you are looking at this point as good. At this moment, we are using this mod: [FS22_MM_Impact](https://forbidden-mods.de/filebase/file/45221-fs22-m18-impact/). In urgent cases, we load this into our repair pickup car and use it for repair on the field. In standard cases, it leans inside the building and works as a normal workshop trigger.

I can imagine that this repair can be "temporary" and definitive repair in the workshop follows in a relatively short time (a few days?). But this is the question if this way is possible. 

Anyway, your idea about calling a worker is good and enough to fix the issue on the field.

When I think around, there is also another way, use your pallet and transport it to the field, and make the repair using it. But, for higher worker price except "normal opening time". 
If I understand, there is no way to repair using a standard workshop trigger, isn't it?

**Comment by Frvetz** [comment]
1. Ohh now I get it. Yeah I can disable the "need motor turned on" and my "engine stalled" warning if you want, but unfortunately there is no way to disable it for every other mod as well. CVT_Addon for example has "need clutch to start" and disabling this with another script is not really possible...
2. You're right, there is no way (at least there shouldn't be) to use the repair button from the standard workshop. I noted your idea and I'm going to have a look at it in the near future. I am probably going to stick to the "call worker" method though, since I think another smaller object for emergency maintenance just confuses people. The "temporary" repair is in theory also a good idea, but I don't really have an idea how to implement this. What happens at a temporary repair? What happens at the full repair later?

:D Gerrit

**Comment by DrewCZ** [comment]
Gerrit, thank you from my whole heart to disable any message appears on the screen. It is very appreciated! Thank you. 
2. Full understand you. My ideas are only ideas. With full respect to your amazing work. Thank you again, also for your open mind and listen my questions. 
Looking for tomorrow, now I'm going to test your mod in our MP environment. In SP I'm sure there be a lot of fun.

**Comment by Frvetz** [comment]
No worries :)

Just found this mod where you can disable the "need motor started" warning: https://www.farming-simulator.com/mod.php?lang=en&country=rs&mod_id=230136

and for my "engine stalled" warning: is it okay if I just send you the edited version here? Since I think not many players need a whole setting in the ESC-menu for that which is quite a lot of work

the edit would be gone though when you update the mod. If you want you can add me on discord #frvetz and write me when you need the text to be removed again

**Comment by DrewCZ** [comment]
Thank you for suggesting the mod. I'll check it.
About your message, I know how to disable print the message on the screen. Thank you. I will manage it. And know that the change must be repeated after update. 
Cheers and happy farming in new year!

**Comment by Frvetz** [comment]
Awesome, thank you as well for the idea!!

Cheers!
